version: 2.1
jobs:
  install_deps:
    docker:
      - image: node:16
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys: 
            - yarn-packages-hooks-lib-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          name: Caching dependencies
          key: yarn-packages-hooks-lib-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  lint:
    docker:
      - image: node:16
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys: 
            - yarn-packages-hooks-lib-{{ checksum "yarn.lock" }}
      - run:
          name: ESLint
          command: yarn lint

  test:
    docker:
      - image: node:16
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys: 
             - yarn-packages-hooks-lib-{{ checksum "yarn.lock" }}
             - yarn-packages-hooks-lib
      - run:
          name: Run Unit Tests
          command: yarn test

  build:
    docker:
      - image: node:16
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys: 
            - yarn-packages-hooks-lib{{ checksum "yarn.lock" }}
            - yarn-packages-hooks-lib
      - run:
          name: Build Source files
          command: yarn build
      - save_cache:
          name: Caching built code
          key: build-hooks-lib-{{ checksum "src" }}
          paths:
            - lib

  deploy:
    docker:
      - image: node:16
    steps:
      - checkout
      - restore_cache:
          name: Restore Build Cache
          keys: 
            - build-hooks-lib-{{ checksum "src" }}
      - run:
          name: Deploy tag to NPM
          command: yarn 
      - run:
          name: Authenticate with registry
          command: echo "https://registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish



workflows:
  version: 2
  main:
    jobs:
      - install_deps
      - lint:
          requires:
            - install_deps
  deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
            branches:
              only: /mistress/
      - deploy:
          context: deploy
          requires:
            - build